[build]
  command = "npm run build"
  publish = "."   # Use repository root for functions-only deployment

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/paid"
  to = "/paid.html"
  status = 200

[[redirects]]
  from = "/api/send"
  to = "/.netlify/functions/email"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
