name: Health check
on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health
        run: |
          curl -fsS "https://elaborate-snickerdoodle-5ec99b.netlify.app/.netlify/functions/health" | jq .
